version: "3.8"

services:
  api:
    container_name: "api"
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src
    networks:
      - local-net
    logging:
      driver: "json-file"
      options:
        max-size: '10m'
        max-file: '10'
networks:
  local-net:
    driver: bridge